#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.50

bspc config focused_border_color "#000000"
bspc config normal_border_color "#ffffff"
bspc config active_border_color "#000000"
bspc config presel_feedback_color "#ffffff"

bspc rule -r *:*
xsetroot -cursor_name left_ptr

# Start compositor
picom &
# Start status bar
polybar &
# Set the background with feh
feh --bg-fill ~/.config/wallpaper.jpg
# Set cursor size to different
xsetroot -cursor_name left_ptr &
